/* rolesテーブル */
INSERT IGNORE INTO roles (id, name) VALUES
(1, 'ROLE_FREE_MEMBER'),
(2, 'ROLE_PAID_MEMBER'),
(3, 'ROLE_ADMIN');

/* usersテーブル */
INSERT IGNORE INTO users (id, name, furigana, email, password, role_id, enabled) VALUES
(1, '侍 太郎', 'サムライ タロウ', 'taro.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 1, true),
(2, '侍 次郎', 'サムライ ジロウ', 'jiro.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 2, true),
(3, '侍 花子', 'サムライ ハナコ', 'hanako.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 3, true),
(4, '山田 太郎', 'ヤマダ タロウ', 'taro.yamada@example.com', 'password', 1, false),
(5, '佐藤 花子', 'サトウ ハナコ', 'hanako.sato@example.com', 'password', 1, false),
(6, '鈴木 一郎', 'スズキ イチロウ', 'ichiro.suzuki@example.com', 'password', 1, false),
(7, '高橋 雅子', 'タカハシ マサコ', 'masako.takahashi@example.com', 'password', 1, false),
(8, '中村 純一', 'ナカムラ ジュンイチ', 'junichi.nakamura@example.com', 'password', 1, false),
(9, '小林 由美子', 'コバヤシ ユミコ', 'yumiko.kobayashi@example.com', 'password', 1, false),
(10, '加藤 仁', 'カトウ ヒトシ', 'hitoshi.kato@example.com', 'password', 1, false),
(11, '吉田 美穂', 'ヨシダ ミホ', 'miho.yoshida@example.com', 'password', 1, false),
(12, '渡辺 翔', 'ワタナベ ショウ', 'sho.watanabe@example.com', 'password', 1, false),
(13, '伊藤 真理', 'イトウ マリ', 'mari.ito@example.com', 'password', 1, false),
(14, '斎藤 雄大', 'サイトウ ユウダイ', 'yudai.saito@example.com', 'password', 1, false),
(15, '田村 里美', 'タムラ サトミ', 'satomi.tamura@example.com', 'password', 1, false),
(16, '金子 智也', 'カネコ トモヤ', 'tomoya.kaneko@example.com', 'password', 1, false),
(17, '山口 真緒', 'ヤマグチ マオ', 'mao.yamaguchi@example.com', 'password', 1, false),
(18, '森 祐太', 'モリ ユウタ', 'yuta.mori@example.com', 'password', 1, false),
(19, '原田 知子', 'ハラダ トモコ', 'tomoko.harada@example.com', 'password', 1, false),
(20, '浜田 翔平', 'ハマダ ショウヘイ', 'shohei.hamada@example.com', 'password', 1, false),
(21, '中川 彩', 'ナカガワ アヤ', 'aya.nakagawa@example.com', 'password', 1, false),
(22, '松本 龍', 'マツモト リュウ', 'ryu.matsumoto@example.com', 'password', 1, false),
(23, '石田 美晴', 'イシダ ミハル', 'miharu.ishida@example.com', 'password', 1, false),
(24, '前田 雄介', 'マエダ ユウスケ', 'yusuke.maeda@example.com', 'password', 1, false),
(25, '岡本 里香', 'オカモト リカ', 'rika.okamoto@example.com', 'password', 1, false),
(26, '吉岡 駿', 'ヨシオカ シュン', 'shun.yoshioka@example.com', 'password', 1, false),
(27, '藤井 美咲', 'フジイ ミサキ', 'misaki.fujii@example.com', 'password', 1, false),
(28, '山内 光', 'ヤマウチ ヒカル', 'hikaru.yamauchi@example.com', 'password', 1, false),
(29, '木村 香', 'キムラ カオリ', 'kaori.kimura@example.com', 'password', 1, false),
(30, '中山 大地', 'ナカヤマ ダイチ','daichi.nakayama@example.com', 'password', 1, false),
(31, '西村 葵', 'ニシムラ アオイ', 'aoi.nishimura@example.com', 'password', 1, false),
(32, '小川 真司', 'オガワ シンジ', 'shinji.ogawa@example.com', 'password', 1, false),
(33, '佐々木 美優', 'ササキ ミユ', 'miyu.sasaki@example.com', 'password', 1, false),
(34, '田辺 雄一', 'タナベ ユウイチ', 'yuichi.tanabe@example.com', 'password', 1, false),
(35, '松井 美希', 'マツイ ミキ', 'miki.matsui@example.com', 'password', 1, false),
(36, '新井 慎太郎', 'アライ シンタロウ', 'shintaro.arai@example.com', 'password', 1, false),
(37, '大塚 美紀', 'オオツカ ミキ', 'miki.otsuka@example.com', 'password', 1, false),
(38, '中島 駿平', 'ナカジマ シュンペイ', 'shunpei.nakajima@example.com', 'password', 1, false),
(39, '加藤 里絵', 'カトウ リエ', 'rie.kato@example.com', 'password', 1, false),
(40, '渡辺 一樹', 'ワタナベ カズキ', 'kazuki.watanabe@example.com', 'password', 1, false),
(41, '斉藤 理絵', 'サイトウ リエ', 'rie.saito@example.com', 'password', 1, false),
(42, '井上 慎吾', 'イノウエ シンゴ', 'shingo.inoue@example.com', 'password', 1, false),
(43, '小林 美智子', 'コバヤシ ミチコ', 'michiko.kobayashi@example.com', 'password', 1, false),
(44, '山田 真二', 'ヤマダ シンジ', 'shinji.yamada@example.com', 'password', 1, false),
(45, '中村 美穂', 'ナカムラ ミホ', 'miho.nakamura@example.com', 'password', 1, false),
(46, '佐藤 達也', 'サトウ タツヤ', 'tatsuya.sato@example.com', 'password', 1, false),
(47, '田中 美緒', 'タナカ ミオ', 'mio.tanaka@example.com', 'password', 1, false),
(48, '鈴木 洋介', 'スズキ ヨウスケ', 'yosuke.suzuki@example.com', 'password', 1, false),
(49, '佐藤 真一', 'サトウ シンイチ', 'shinichi.sato@example.com', 'password', 1, false),
(50, '山本 昭二', 'ヤマモト ショウジ', 'shoji.yamamoto@example.com', 'password', 1, false),
(51, '井口 美和', 'イグチ ミワ', 'miwa.iguchi@example.com', 'password', 1, false),
(52, '山口 真紀', 'ヤマグチ マキ', 'maki.yamaguchi@example.com', 'password', 1, false),
(53, '井上 祐一', 'イノウエ ユウイチ', 'yuichi.inoue@example.com', 'password', 1, false),
(54, '斉藤 裕子', 'サイトウ ヒロコ', 'hiroko.saito@example.com', 'password', 1, false),
(55, '佐藤 慎吾', 'サトウ シンゴ', 'shingo.sato@example.com', 'password', 1, false),
(56, '小林 一樹', 'コバヤシ カズキ', 'kazuki.kobayashi@example.com', 'password', 1, false),
(57, '山田 美智子', 'ヤマダ ミチコ', 'michiko.yamada@example.com', 'password', 1, false),
(58, '中村 駿平', 'ナカムラ シュンペイ', 'shunpei.nakamura@example.com', 'password', 1, false),
(59, '斎藤 美紀', 'サイトウ ミキ', 'miki.saito@example.com', 'password', 1, false),
(60, '佐々木 真一', 'ササキ シンイチ', 'shinichi.sasaki@example.com', 'password', 1, false),
(61, '渡辺 美穂', 'ワタナベ ミホ', 'miho.watanabe@example.com', 'password', 1, false),
(62, '高橋 裕也', 'タカハシ ヒロヤ', 'hiroya.takahashi@example.com', 'password', 1, false),
(63, '山口 美智子', 'ヤマグチ ミチコ', 'michiko.yamaguchi@example.com', 'password', 1, false),
(64, '井上 真二', 'イノウエ シンジ', 'shinji.inoue@example.com', 'password', 1, false),
(65, '斉藤 美穂', 'サイトウ ミホ', 'miho.saito@example.com', 'password', 1, false),
(66, '鈴木 美紀', 'スズキ ミキ', 'miki.suzuki@example.com', 'password', 1, false),
(67, '中村 明美', 'ナカムラ アケミ', 'akemi.nakamura@example.com', 'password', 1, false),
(68, '木村 健太', 'キムラ ケンタ', 'kenta.kimura@example.com', 'password', 1, false),
(69, '吉田 美由紀', 'ヨシダ ミユキ','miyuki.yoshida@example.com', 'password', 1, false),
(70, '鈴木 義司', 'スズキ ヨシハル', 'yoshiharu.suzuki@example.com', 'password', 1, false),
(71, '高田 真理子', 'タカダ マリコ', 'mariko.takada@example.com', 'password', 1, false),
(72, '今井 真一', 'イマイ シンイチ', 'shinichi.imai@example.com', 'password', 1, false),
(73, '上田 美穂', 'ウエダ ミホ', 'miho.ueda@example.com', 'password', 1, false),
(74, '岡田 健太', 'オカダ ケンタ', 'kenta.okada@example.com', 'password', 1, false),
(75, '佐藤 一郎', 'サトウ イチロウ', 'ichiro.sato@example.com', 'password', 1, false),
(76, '高橋 直子', 'タカハシ ナオコ', 'naoko.takahashi@example.com', 'password', 1, false),
(77, '田中 充', 'タナカ ミツル', 'mitsuru.tanaka@example.com', 'password', 1, false),
(78, '渡辺 静香', 'ワタナベ シズカ', 'shizuka.watanabe@example.com', 'password', 1, false),
(79, '伊藤 純一', 'イトウ ジュンイチ', 'junichi.ito@example.com', 'password', 1, false),
(80, '山本 美奈子', 'ヤマモト ミナコ', 'minako.yamamoto@example.com', 'password', 1, false),
(81, '中島 勇人', 'ナカジマ ユウト', 'yuto.nakajima@example.com', 'password', 1, false),
(82, '小林 里美', 'コバヤシ サトミ', 'satomi.kobayashi@example.com', 'password', 1, false),
(83, '吉田 真治', 'ヨシダ シンジ', 'shinji.yoshida@example.com', 'password', 1, false),
(84, '山田 淳子', 'ヤマダ ジュンコ', 'junko.yamada@example.com', 'password', 1, false),
(85, '斎藤 幸雄', 'サイトウ ユキオ', 'yukio.saito@example.com', 'password', 1, false),
(86, '鈴木 由紀', 'スズキ ユキ', 'yuki.suzuki@example.com', 'password', 1, false),
(87, '高野 明美', 'タカノ アケミ', 'akemi.takano@example.com', 'password', 1, false),
(88, '中村 昌也', 'ナカムラ マサヤ', 'masaya.nakamura@example.com', 'password', 1, false),
(89, '木村 知子', 'キムラ トモコ', 'tomoko.kimura@example.com', 'password', 1, false),
(90, '林 義人', 'ハヤシ ヨシト', 'yoshito.hayashi@example.com', 'password', 1, false),
(91, '田中 花子', 'タナカ ハナコ', 'hanako.tanaka@example.com', 'password', 1, false),
(92, '佐々木 次郎', 'ササキ ジロウ', 'jiro.sasaki@example.com', 'password', 1, false),
(93, '石井 真一', 'イシイ シンイチ', 'shinichi.ishii@example.com', 'password', 1, false),
(94, '小林 美穂', 'コバヤシ ミホ', 'miho.kobayashi@example.com', 'password', 1, false),
(95, '中島 和也', 'ナカジマ カズヤ', 'kazuya.nakajima@example.com', 'password', 1, false),
(96, '松本 純子', 'マツモト ジュンコ', 'junko.matsumoto@example.com', 'password', 1, false),
(97, '石川 良太', 'イシカワ リョウタ', 'ryota.ishikawa@example.com', 'password', 1, false),
(98, '吉岡 里帆', 'ヨシオカ リホ', 'riho.yoshioka@example.com', 'password', 1, false),
(99, '福田 順二', 'フクダ ジュンジ', 'junji.fukuda@example.com', 'password', 1, false),
(100, '石田 花音', 'イシダ カノン', 'kanon.ishida@example.com', 'password', 1, false);